version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6

    steps:
      - checkout
      - run:
          name: install-deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ./node_modules/ember-cli/bin/ember deploy production
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t noslouch/wedding-ember .
      - run: docker push noslouch/wedding-ember
      - run: ssh bwhitton@melissaandbriangetmarried.com "docker pull noslouch/wedding-ember && docker stop wedding && docker rm wedding && docker run --name wedding --restart always -d -p 8001:8001 noslouch/wedding-ember"
