version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
        environment:
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_BUCKET: $AWS_BUCKET
          AWS_REGION: $AWS_REGION

    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --build-arg FINGERPRINT_PREPEND_URL=$FINGERPRINT_PREPEND_URL -t noslouch/wedding-ember .
      - run: docker push noslouch/wedding-ember

      - deploy:
          name: ship ember assets
          command: ./node_modules/ember-cli/bin/ember deploy production 

      - deploy:
          name: pull down docker image
          command: |
            ssh-keyscan melissaandbriangetmarried.com >> ~/.ssh/known_hosts
            ssh bwhitton@melissaandbriangetmarried.com "docker pull noslouch/wedding-ember && docker stop wedding && docker rm wedding && docker run --name wedding --restart always -d -p 8001:8001 noslouch/wedding-ember" 
