version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t noslouch/wedding-ember .
      - run: docker push noslouch/wedding-ember
      - run: ssh bwhitton@melissaandbriangetmarried.com "docker pull noslouch/wedding-ember && docker stop wedding && docker rm wedding && docker run --name wedding --restart always -d -p 8001:8001 noslouch/wedding-ember"
